FROM openjdk:17

WORKDIR /app

COPY target/lms_security-0.0.1-SNAPSHOT.jar /app/app.jar
COPY target/wait.sh /app/cekaj.sh

RUN chmod +x /app/cekaj.sh

CMD ["/app/cekaj.sh", "java", "-jar", "/app/app.jar"]