
# upstream mikroservis {
# 	server mikrov:8084;
# }

# upstream natasa {
# 	server app-nereg1:1730;
# }

# upstream jelisej {
# 	server app-nereg2:1731;
# }

upstream security {
	server lms-app-security:1732;
}

upstream univerzitet {
	server lms-app-univerzitet:1733;
}

upstream fakultet {
	server lms-app-fakultet:1734;
}

upstream ispit {
	server lms-app-ispit:1735;
}

upstream kc {
	server keycloak:8080;
}

server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

	location / {
		root   /usr/share/nginx/html/lms/browser;
    }

	location /keycloak {
	    proxy_set_header Host $host;
	    proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	    proxy_set_header X-Forwarded-Proto $scheme;
	    proxy_buffering off;
	    proxy_request_buffering off;
	    proxy_http_version 1.1;
	    proxy_intercept_errors on;
		proxy_pass http://kc;
	}

	location /api/security {
	    proxy_set_header Host $host;
	    proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	    proxy_set_header X-Forwarded-Proto $scheme;
	    proxy_buffering off;
	    proxy_request_buffering off;
	    proxy_http_version 1.1;
	    proxy_intercept_errors on;
		proxy_pass http://security;
	}

	location /api/univerzitet {
	    proxy_set_header Host $host;
	    proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	    proxy_set_header X-Forwarded-Proto $scheme;
	    proxy_buffering off;
	    proxy_request_buffering off;
	    proxy_http_version 1.1;
	    proxy_intercept_errors on;
		proxy_pass http://univerzitet;
	}
	location /api/fakultet {
	    proxy_set_header Host $host;
	    proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	    proxy_set_header X-Forwarded-Proto $scheme;
	    proxy_buffering off;
	    proxy_request_buffering off;
	    proxy_http_version 1.1;
	    proxy_intercept_errors on;
		proxy_pass http://fakultet;
	}
	location /api/ispit {
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_buffering off;
		proxy_request_buffering off;
		proxy_http_version 1.1;
		proxy_intercept_errors on;
		proxy_pass http://ispit;
	}

    # location / {
	#     proxy_set_header Host $host;
	#     proxy_set_header X-Real-IP $remote_addr;
	#     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	#     proxy_set_header X-Forwarded-Proto $scheme;
	#     proxy_buffering off;
	#     proxy_request_buffering off;
	#     proxy_http_version 1.1;
	#     proxy_intercept_errors on;
	#     proxy_pass http://mikroservis/;
    # }	

    # location  /api/n {
	#     proxy_set_header Host $host;
	#     proxy_set_header X-Real-IP $remote_addr;
	#     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	#     proxy_set_header X-Forwarded-Proto $scheme;
	#     proxy_buffering off;
	#     proxy_request_buffering off;
	#     proxy_http_version 1.1;
	#     proxy_intercept_errors on;
	#     proxy_pass http://natasa;
    # }
    
    # location  /api/j {
	#     proxy_set_header Host $host;
	#     proxy_set_header X-Real-IP $remote_addr;
	#     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	#     proxy_set_header X-Forwarded-Proto $scheme;
	#     proxy_buffering off;
	#     proxy_request_buffering off;
	#     proxy_http_version 1.1;
	#     proxy_intercept_errors on;
	#     proxy_pass http://jelisej;
    # }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

}

