spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true

spring.jackson.default-property-inclusion = non_null

spring.datasource.url=jdbc:mysql://host.containers.internal:3306/spring-predmet
#spring.datasource.url=jdbc:mysql://localhost:3306/spring-predmet
spring.datasource.username=test
spring.datasource.password=?TestTset7

server.port=1731
spring.application.name=nereg2
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#token.secret=LSAK\qw'/sad'[\}ALSJSDKL34L134K;3LKR3!$#!4WaSLDAD@tassDPOQE
#token.expiration=3600