spring.config.import=db.properties

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true

spring.jackson.default-property-inclusion = non_null

server.port=1735
spring.application.name=ispit
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true